Repository SWCF-8TEAM/taskify, pull requests merged in 2023-12, with the labels that each got.

#4 🧹chore: gitignore 적용 안되는 문제 해결 위해 .next 캐쉬 제거
  .next/cache/webpack/client-development/0.pack.gz
  .next/cache/webpack/client-development/index.pack.gz
  .next/cache/webpack/server-development/0.pack.gz
  .next/cache/webpack/server-development/index.pack.gz
  .next/server/pages/_app.js
  .next/server/pages/_error.js
  .next/server/pages/index.js
  .next/static/chunks/pages/_app.js
  .next/static/chunks/pages/index.js
  .next/static/chunks/webpack.js
  .next/trace
Labels: 🧹chore

#5 💫Feat: input layout
  assets/icons/large-logo.svg
  assets/icons/main-logo.svg
  assets/icons/small-logo.svg
  components/SignInForm.tsx
  components/SignInput/Input.tsx
  components/SignInput/PasswordInput.tsx
  components/SignUpForm.tsx
  components/components.tsx
  package-lock.json
  package.json
  pages/index.tsx
  styles/ColorStyles.ts
  tsconfig.json
  utils/InputConstant.ts
Labels: 💫feat

#9 🍀 refactor: chip 컴포넌트 리팩토링
  components/Chip/AddColumn.tsx
  components/Chip/ColumnName.tsx
  components/Chip/DashBoardColor.tsx
  states/atoms.tsx
Labels: 🍀refactor

#11 🧹chore: 빌드파일 무시하도록 수정
  .gitignore
Labels: 🧹chore

#14 🍀refactor: button 컴포넌트 리팩토링
  components/ButtonSet/ButtonSet.tsx
  components/button/Button.tsx
  components/button/ButtonStyles.ts
  components/button/mockData.ts
Labels: 🍀refactor

#15 💫Feat: 모달 인풋
  components/ModalInput/ModalInput.tsx
Labels: 💫feat

#10 🍀refactor: header 컴포넌트 리팩토링
  components/Nav/NavContainer.tsx
  components/Nav/ProfileImages.tsx
  package-lock.json
  package.json
  pages/index.tsx
Labels: 🍀refactor

#16 💫 Feat: card component 구현
  api/api.ts
  api/axios.tsx
  assets/icons/blue-circle.svg
  components/Card/Card.tsx
  components/Column/Column.tsx
  components/Column/ColumnHeader.tsx
  components/Column/Columns.tsx
  components/button/Button.tsx
  pages/dashboard/index.tsx
  styles/ColorStyles.ts
  utils/FormatDate.ts
  utils/utils.ts
Labels: 💫feat

#17 💫 feat: 상태 dropdown 구현
  assets/icons/check.svg
  components/ModalInput/DropdownList.tsx
  components/ModalInput/StateDropdown.tsx
  styles/GlobalStyles.ts
Labels: 💫feat

#18 🛠️Fix: 미디어 쿼리 적용, 사이즈 프롭 삭제
  components/ButtonSet/ButtonSet.tsx
  components/ButtonSet/ButtonSetStyles.ts
  components/button/Button.tsx
  components/button/ButtonStyles.ts
Labels: 🛠️fix

#19 💫 feat: table 컴포넌트 구현
  components/Chip/AddColumn.tsx
  components/Chip/ColumnName.tsx
  components/Chip/DashBoardColor.tsx
  components/SearchInput.tsx
  components/Table/InvitationHistory.tsx
  components/Table/InvitedDashboard.tsx
  components/Table/Member.tsx
  pages/index.tsx
Labels: 💫feat

#20 🍀 refactor: table 컴포넌트 리팩토링
  components/Chip/AddColumn.tsx
  components/Table/InvitationHistory.tsx
  components/Table/InvitedDashboard.tsx
  components/Table/Member.tsx
Labels: 🍀refactor

#24 🍀 refactor: 버튼 프롭 수정
  components/button/Button.tsx
Labels: 🍀refactor

#21 🍀 refactor: 대시보드 리스트 버튼 데이터 적용 및 테스트 내용 삭제
  pages/index.tsx
Labels: 🍀refactor

#22 💫 feat : NoProfileImage 컴포넌트 구현
  components/Card/Card.tsx
  components/NoProfileImage/ProfileImage.tsx
Labels: 💫feat

#23 🍀 refactor: card component
  components/Card/Card.tsx
  components/Column/Column.tsx
  components/Column/Columns.tsx
Labels: 🍀refactor

#29 🍀 refactor: 모달 인풋 리팩토링
  components/ModalInput/ModalInput.tsx
  package-lock.json
  package.json
Labels: 🤯help, 🍀refactor

#26 💫 feat: modal tag input 구현
  components/ModalInput/TagInput.tsx
Labels: 💫feat

#28 💫 feat: 담당자 드롭다운 구현
  components/ModalInput/ContactDropdown.tsx
Labels: 💫feat

#33 💫 feat: 모달 컴포넌트 구현
  components/Modal/AlertModal.tsx
  components/Modal/ColumnCreateModal.tsx
  components/Modal/ColumnManagingModal.tsx
  components/Modal/DeleteConfirmModal.tsx
  components/Modal/KebabModal.tsx
  components/Modal/NameInput.tsx
  components/Modal/NewDashBoardModal.tsx
  components/Modal/TodoModal.tsx
  components/button/Button.tsx
  pages/index.tsx
Labels: 💫feat, 🤯help

#36 🍀 refactor: 소희님 작업 버튼 컴포넌트 리팩토링
  components/ButtonSet/ButtonSet.tsx
  components/ButtonSet/ButtonSetStyles.ts
  components/button/Button.tsx
  components/button/ButtonStyles.ts
Labels: 🍀refactor

#34 🍀 refactor: Modal tag컴포넌트 리팩토링
  components/ModalInput/TagInput.tsx
Labels: 🍀refactor

#35 🍀 refactor: 슬님 작업 컴포넌트 리팩토링
  assets/icons/circle.svg
  components/Chip/AddColumn.tsx
  components/Chip/ColumnName.tsx
  components/Chip/CounterCard.tsx
  components/Chip/DashBoardColor.tsx
  components/Chip/Tag.tsx
  components/ModalInput/ContactDropdown.tsx
  components/Table/InvitationHistory.tsx
  components/Table/InvitedDashboard.tsx
  components/Table/Member.tsx
Labels: 🍀refactor

#38 🍀 refactor: 지은님 작업 컴포넌트 리팩토링
  components/Card/Card.tsx
  components/Column/Column.tsx
  components/Column/ColumnHeader.tsx
  components/Column/Columns.tsx
  pages/index.tsx
Labels: 🍀refactor

#37 🍀 refactor: 혜윤님 컴포넌트 수정 완료
  components/Modal/AlertModal.tsx
  components/Modal/ColumnCreateModal.tsx
  components/Modal/ColumnManagingModal.tsx
  components/Modal/CreateColumnModal.tsx
  components/Modal/DeleteConfirmModal.tsx
  components/Modal/KebabModal.tsx
  components/Modal/ManageColumnModal.tsx
  components/Modal/ModalContainer.tsx
  components/Modal/NameInput.tsx
  components/Modal/NewDashBoardModal.tsx
  components/Modal/TodoModal.tsx
  components/ModalInput/ModalInput.tsx
  package-lock.json
Labels: 🍀refactor

#39 🍀 refactor: transient props 달러 사인 추가
  components/ButtonSet/ButtonSet.tsx
  components/ModalInput/ModalInput.tsx
Labels: 🍀refactor

#43 🍀 refactor: 모달 인풋 - 설명 영역 추가 및 기존 인풋 리팩토링 + 이미지 첨부 인풋 추가
  assets/icons/add-fillo.svg
  assets/icons/edit.svg
  components/ModalInput/ImageUploadInput.tsx
  components/ModalInput/ModalInput.tsx
  components/ModalInput/TagInput.tsx
Labels: 💫feat, 🍀refactor

#49 💫 feat: 대시보드 초대 받은 내역 없는 상태 구현
  assets/icons/unsubscribe-envelop.png
  assets/icons/unsubscribe-envelope.svg
  components/Table/NoInvite.tsx
Labels: 💫feat

#41 🍀 refactor: 변경된 디자인에 맞게 리팩토링
  assets/icons/email-envelope.svg
  assets/icons/facebook.svg
  assets/icons/instagram.svg
  components/Table/InvitationHistory.tsx
  components/Table/InvitedDashboard.tsx
Labels: 🍀refactor

#32 💫 feat: 랜딩페이지 구현
  assets/icons/large-logo.svg
  assets/images/blue-img.svg
  assets/images/green-img.svg
  assets/images/landing-main.png
  assets/images/landing1.png
  assets/images/landing2.png
  assets/images/landing3.png
  assets/images/landing4.png
  assets/images/landing5.png
  assets/images/purple-img.svg
  assets/images/yellow-img.svg
  components/Landing/MainSection.tsx
  components/Landing/Point1.tsx
  components/Landing/Point2.tsx
  components/Landing/Setting.tsx
  pages/index.tsx
Labels: 💫feat

#42 🍀 refactor: input 컴포넌트 변경사항에 맞게 리팩토링
  components/SignForm/SignInForm.tsx
  components/SignForm/SignUpForm.tsx
  components/SignInput/PasswordInput.tsx
  constants/InputConstant.ts
Labels: 🍀refactor

#44 🍀 refactor: header, sidemenu 컴포넌트 변경사항에 맞게 리팩토링
  components/Nav/DashboardButtons.tsx
  components/Nav/DashboradNav.tsx
  components/Nav/MainNav.tsx
  components/Nav/MyDashboardNav.tsx
  components/Nav/NavContainer.tsx
  components/Nav/Profile.tsx
  components/Nav/ProfileImages.tsx
  components/Nav/SettingNav.tsx
  components/Nav/mockData.ts
  components/NoProfileImage/ProfileImage.tsx
  components/SideMenu/SettingSideMenu.tsx
  components/SideMenu/SideMenu.tsx
  components/common/LogoButton.tsx
  styles/ColorStyles.ts
Labels: 🍀refactor

#45 💫 feat: 사용자 프로필 관련 메뉴 구현
  components/Nav/Profile.tsx
  package-lock.json
  package.json
Labels: 💫feat

#46 🎨 ui: 서비스명 및 로고 변경
  assets/icons/large-logo.svg
  assets/icons/main-logo.svg
  assets/icons/small-logo.svg
Labels: 🎨UI

#47 💫 feat: 대시보드 멤버 리스트 띄우기
  components/Nav/MemberListDropdown.tsx
  components/Nav/ProfileImages.tsx
  components/Nav/mockData.ts
Labels: 💫feat

#48 💫 feat: 계정관리 - 프로필 / 비밀번호 관리 컴포넌트 추가 구현
  components/Account/AccountPassword.tsx
  components/Account/AccountProfile.tsx
  components/ModalInput/ImageUploadInput.tsx
Labels: 💫feat, 🤯help

#50 🎨 ui: SignInPage, SignUpPage 레이아웃 구현
  pages/signin/index.tsx
  pages/signup/index.tsx
Labels: 💫feat, 🎨UI

#51 🍀 refactor : useMemo, useCallback 삭제
  components/ModalInput/TagInput.tsx
Labels: 🍀refactor

#52 🍀 refactor : 글자모달 수정, 대왕모달 만들기
  assets/icons/category-division.svg
  components/Dashboard/Column/Columns.tsx
  components/Modal/AlertModal.tsx
  components/Modal/TaskModal.tsx
  components/Modal/TodoModal.tsx
  utils/FormatDate.ts
Labels: 🍀refactor

#54 💫 feat: /mydashboard 페이지 구현
  api/dashboards/getDashboardList.ts
  components/Dashboard/Column/Columns.tsx
  components/MyDashboardList.tsx
  components/Table/InvitedDashboard.tsx
  components/Table/NoInvite.tsx
  components/common/Buttons/Button.tsx
  pages/mydashboard/index.tsx
Labels: 💫feat

#55 🍀 refactor: 랜딩페이지 색 변경
  components/Landing/MainSection.tsx
  components/Landing/Setting.tsx
Labels: 🍀refactor

#56 🍀 refactor: nav 프로필 리팩토링
  components/common/Nav/MemberListDropdown.tsx
  components/common/Nav/Profile.tsx
  components/common/Nav/ProfileImages.tsx
  states/atoms.tsx
Labels: 🍀refactor

#58 🧹 chore: API폴더구조 개선
  api/auth/index.ts
  api/auth/postLogin.ts
  api/cards/deleteCard.ts
  api/cards/getCard.ts
  api/cards/getCardList.ts
  api/cards/index.ts
  api/cards/postCard.ts
  api/cards/putCard.ts
  api/columns/deleteColumns.ts
  api/columns/getColumns.ts
  api/columns/index.ts
  api/columns/postCardImage.ts
  api/columns/postColumns.ts
  api/columns/putColumns.ts
  api/comments/deleteComments.ts
  api/comments/getComments.ts
  api/comments/index.ts
  api/comments/postComments.ts
  api/comments/putComments.ts
  api/dashboards/deleteDashboard.ts
  api/dashboards/deleteDashboardInvitations.ts
  api/dashboards/getDashboard.ts
  api/dashboards/getDashboardInvitations.ts
  api/dashboards/getDashboardList.ts
  api/dashboards/index.ts
  api/dashboards/postDashboard.ts
  api/dashboards/postDashboardInvitations.ts
  api/dashboards/putDashboard.ts
  api/invitations/getInvitations.ts
  api/invitations/index.ts
  api/invitations/putInvitations.ts
  api/members/deleteMembers.ts
  api/members/index.ts
  api/users/getUsers.ts
  api/users/index.ts
  api/users/postProfileImage.ts
  api/users/postUsers.ts
  api/users/putUsers.ts
Labels: 🧹chore, 🍀refactor

#57 🍀 refactor: Task Modal 리팩토링
  components/Modal/TaskModal.tsx
  components/Modal/mockData.ts
  pages/index.tsx
  styles/ZindexStyles.ts
Labels: 🤯help, 🍀refactor

#59 🍀 refactor: getDashboardList api 수정
  api/dashboards/dashboards.types.ts
  api/dashboards/index.ts
  components/MyDashboardList.tsx
Labels: 🍀refactor

#60 🍀 refactor: signin/signup 페이지 세부 수정사항 반영
  components/Sign/SignForm/SignInForm.tsx
  components/Sign/SignInput/Input.tsx
  pages/signin/index.tsx
  pages/signup/index.tsx
Labels: 🍀refactor

#62 💫 feat: 계정관리 페이지 구현
  components/Account/AccountPassword.tsx
  components/Account/AccountProfile.tsx
  components/Sign/SignForm/SignInForm.tsx
  components/Sign/SignForm/SignUpForm.tsx
  components/Sign/SignInput/Input.tsx
  components/Sign/SignInput/PasswordInput.tsx
  components/common/Buttons/BackButton.tsx
  pages/mypage/index.tsx
Labels: 💫feat, 🍀refactor

#61 💫 feat: 대시보드 수정 페이지 구현
  components/Table/EditDashboard.tsx
  components/Table/InvitationHistory.tsx
  components/Table/MemberList.tsx
  components/common/Buttons/BackButton.tsx
  components/common/Buttons/ButtonSet.tsx
  components/common/Buttons/ButtonSetStyles.ts
  components/common/Nav/NavContainer.tsx
  next.config.js
  pages/dashboard/[boardid]/edit.tsx
Labels: 💫feat, 🍀refactor

#63 💫 feat: 대시보드 페이지 구현
  components/Dashboard/Column/ColumnHeader.tsx
  components/Dashboard/Column/Columns.tsx
  components/MyDashboardList.tsx
  components/common/Nav/DashboardNav.tsx
  components/common/SideMenu/SideMenu.tsx
  pages/dashboard/index.tsx
Labels: 💫feat

#64 💫 feat: 새로운 대시보드 생성 시 모달 띄우고 취소 버튼 누를 시 닫히도록 구현
  components/Modal/ModalContainer.tsx
  components/MyDashboardList.tsx
  components/common/Buttons/Button.tsx
  components/common/Buttons/ButtonSet.tsx
Labels: 💫feat

#66 💫 feat: 초대받은 대시보드 데이터 불러온 후 수락 거절 기능 구현
  api/config.ts
  api/invitations/index.ts
  api/invitations/invitations.types.ts
  components/Table/InvitedDashboard.tsx
  components/common/Buttons/ButtonSet.tsx
Labels: 💫feat

#67 💫 feat: 무한 스크롤 구현
  api/cards/cards.types.ts
  hooks/hooks.ts
  hooks/useScroll.ts
  pages/scroll-test.tsx
Labels: 💫feat

#65 💫 feat: 모달 기능 구현
  api/cards/cards.types.ts
  api/comments/comments.types.ts
  components/Modal/ModalInput/ModalInput.tsx
  components/Modal/ModalInput/TagInput.tsx
  components/Modal/TaskModal.tsx
  components/Modal/TodoModal.tsx
  components/common/Buttons/ButtonStyles.ts
  package-lock.json
  package.json
  pages/index.tsx
  styles/ZindexStyles.ts
Labels: 💫feat, 🤯help

#69 💫 feat: signpage 기능 구현
  api/auth/auth.types.ts
  api/auth/index.ts
  api/users/index.ts
  api/users/users.types.ts
  components/Modal/AlertModal.tsx
  components/Modal/ModalWrapper.tsx
  components/Sign/SignForm/SignInForm.tsx
  components/Sign/SignForm/SignUpForm.tsx
  components/Sign/SignInput/PasswordInput.tsx
  components/common/Nav/SignButton.tsx
  constants/InputConstant.ts
  hooks/useModal.ts
  pages/index.tsx
  pages/signin/index.tsx
  pages/signup/index.tsx
Labels: 💫feat

#70 💫feat: 대시보드 변경 버튼 클릭시 토스트 띄우기
  components/Dashboard/Column/Columns.tsx
  components/Modal/ToastModal.tsx
  components/Table/EditDashboard.tsx
  package-lock.json
  package.json
  pages/dashboard/index.tsx
Labels: 💫feat

#71 💫feat: boardId 페이지의 카드 목록을 목데이터 → API를 받도록 수정
  api/cards/cards.types.ts
  components/Dashboard/Card/Card.tsx
  components/Dashboard/Column/Column.tsx
  components/Dashboard/Column/Columns.tsx
Labels: 💫feat

#72 💫 feat: 초대받은 대시보드 변경사항 시 페이지 전체가 랜더링 되도록 전역변수 사용
  api/dashboards/index.ts
  components/Modal/ModalContainer.tsx
  components/MyDashboardList.tsx
  components/Table/InvitedDashboard.tsx
  components/common/Nav/Profile.tsx
  components/common/SideMenu/SideMenu.tsx
  states/atoms.tsx
  styles/ZindexStyles.ts
Labels: 💫feat

#73 💫 feat: header 기능 구현
  api/dashboards/dashboards.types.ts
  api/dashboards/index.ts
  api/members/members.types.ts
  api/users/index.ts
  components/common/Nav/DashboardButtons.tsx
  components/common/Nav/DashboardNav.tsx
  components/common/Nav/MemberListDropdown.tsx
  components/common/Nav/NavContainer.tsx
  components/common/Nav/Profile.tsx
  components/common/Nav/ProfileImages.tsx
  components/common/Nav/SettingNav.tsx
  components/common/Nav/mockData.ts
  components/common/NoProfileImage/ProfileImage.tsx
  package-lock.json
  pages/index.tsx
Labels: 💫feat

#74 💫 feat: mypage 기능 구현
  api/auth/auth.types.ts
  api/auth/index.ts
  api/users/index.ts
  api/users/users.types.ts
  components/Account/AccountPassword.tsx
  components/Account/AccountProfile.tsx
  components/Modal/AlertModal.tsx
  components/MyDashboardList.tsx
  components/Sign/SignForm/SignUpForm.tsx
  components/Sign/SignInput/Input.tsx
  components/common/Buttons/BackButton.tsx
  components/common/Buttons/LogoButton.tsx
  components/common/Nav/MainNav.tsx
  components/common/SideMenu/SettingSideMenu.tsx
  constants/InputConstant.ts
  pages/_app.tsx
  pages/mypage/index.tsx
  public/logo.svg
Labels: 💫feat, 🍀refactor

#75 🍀 refactor: 대시보드 생성 시 칼라 선택 되도록 리팩토링, 전역변수 삭제
  assets/icons/check.svg
  components/Modal/ModalContainer.tsx
  components/Modal/ModalInput/ContactDropdown.tsx
  components/MyDashboardList.tsx
  components/common/Chip/DashBoardColor.tsx
  states/atoms.tsx
Labels: 🍀refactor

#77 💫 feat: sidemenu 기능 구현
  api/dashboards/dashboards.types.ts
  components/common/SideMenu/SideMenu.tsx
  components/common/SideMenu/mockData.ts
Labels: 💫feat

#81 💫 feat : Tag 랜덤색상 구현
  components/Dashboard/Card/Card.tsx
  components/Modal/ModalInput/TagInput.tsx
  components/common/Chip/Tag.tsx
  components/common/NoProfileImage/ProfileImage.tsx
  constants/ColorConstant.ts
Labels: 💫feat

#82 💫 feat: sign페이지, 헤더 Profile
  components/Sign/SignForm/SignInForm.tsx
  components/Sign/SignForm/SignUpForm.tsx
  components/common/Nav/Profile.tsx
  hooks/useIsSignin.ts
  pages/signin/index.tsx
  pages/signup/index.tsx
Labels: 💫feat

#83 💫 feat: 대시보드에 있는 + 버튼 누르면 할 일 모달 오픈, 카드 누르면 상세 모양 모달 오픈
  api/columns/columns.types.ts
  components/Dashboard/Card/Card.tsx
  components/Dashboard/Column/Column.tsx
  components/Dashboard/Column/Columns.tsx
Labels: 💫feat

#84 💫 feat: 댓글 수정 기능 textarea 및 form으로 적용
  components/Modal/TaskModal.tsx
Labels: 💫feat

#85 💫 refactor: 대시보드 케밥, 모달 기능 수정
  api/columns/columns.types.ts
  components/Dashboard/Column/ColumnHeader.tsx
  components/Modal/AlertModal.tsx
  components/Modal/KebabModal.tsx
  components/Modal/TodoModal.tsx
Labels: 🍀refactor

#87 💫 feat: TaskModal 데이터 받아오기 및 적용 구현
  api/cards/cards.types.ts
  api/cards/index.ts
  api/comments/comments.types.ts
  components/Dashboard/Card/Card.tsx
  components/Modal/TaskModal.tsx
Labels: 💫feat

#88 💫 feat: mydashboard 페이지 기능
  api/dashboards/dashboards.types.ts
  api/dashboards/index.ts
  api/invitations/invitations.types.ts
  components/Dashboard/Column/Columns.tsx
  components/Modal/ChangeColumnNameModal.tsx
  components/Modal/KebabModal.tsx
  components/Modal/ModalContainer.tsx
  components/Modal/ModalWrapper.tsx
  components/Modal/TaskModal.tsx
  components/MyDashboardList.tsx
  components/Table/InvitedDashboard.tsx
  components/common/Buttons/Button.tsx
  components/common/Buttons/ButtonSet.tsx
  components/common/Chip/DashBoardColor.tsx
  constants/ColorConstant.ts
  hooks/useInfiniteScroll.ts
  hooks/useInfiniteScrollNavigator.ts
  hooks/usePagination.ts
  hooks/useScroll.ts
  package-lock.json
  package.json
  pages/mydashboard/index.tsx
  pages/scroll-test.tsx
  states/atoms.tsx
  utils/FormatDate.ts
Labels: 💫feat, 🍀refactor

#89 🍀 refactor: taskmodal 리팩
  api/comments/index.ts
  components/Dashboard/Card/Card.tsx
  components/Modal/TaskModal.tsx
Labels: 🍀refactor
