Repository SWCF-8TEAM/taskify, pull requests merged in 2024-01, with the labels that each got.

#92 💫 feat: 테스크 모달 수정하기,삭제하기 기능들
  api/cards/cards.types.ts
  components/Dashboard/Card/Card.tsx
  components/Dashboard/Column/Column.tsx
  components/Modal/EditTaskModal.tsx
  components/Modal/ModalInput/ModalInput.tsx
  components/Modal/TaskDropdown.tsx
  components/Modal/TaskModal.tsx
  states/atoms.tsx
Labels: 💫feat

#90 💫 feat: 할 일 생성 모달 데이터 연동
  api/cards/cards.types.ts
  api/members/index.ts
  components/Dashboard/Column/Column.tsx
  components/Modal/AddTaskModal.tsx
  components/Modal/ModalInput/ContactDropdown.tsx
  components/Modal/ModalInput/ImageUploadInput.tsx
  components/Modal/ModalInput/ModalInput.tsx
  components/Modal/TaskModal.tsx
  components/Modal/mockData.ts
  styles/ZindexStyles.ts
Labels: 💫feat, 🤯help

#93 🍀 refactor: taskModal 리팩토링
  components/Dashboard/Card/Card.tsx
  components/Modal/KebabModal.tsx
  components/Modal/ModalInput/ModalInput.tsx
  components/Modal/TaskModal.tsx
  components/Modal/TaskModal/Comments.tsx
  components/Modal/TaskModal/TaskModal.tsx
  components/Table/InvitedDashboard.tsx
  states/atoms.tsx
Labels: 🍀refactor

#96 💫feat: 할 일 수정 모달 데이터 현재 다 불러온 후 변경사항 저장 중
  api/cards/cards.types.ts
  api/columns/columns.types.ts
  components/Modal/AddTaskModal.tsx
  components/Modal/EditTaskModal.tsx
  components/Modal/ModalInput/ContactDropdown.tsx
  components/Modal/ModalInput/DropdownList.tsx
  components/Modal/ModalInput/ImageUploadInput.tsx
  components/Modal/ModalInput/ModalInput.tsx
  components/Modal/ModalInput/StateDropdown.tsx
  components/Modal/ModalInput/TagInput.tsx
Labels: 💫feat, 🤯help

#94 💫feat: Side-Menu 팝업 닫는 기능, UI수정, API연결(진행중)
  components/common/SideMenu/SideMenu.tsx
Labels: 💫feat, 🤯help

#97 💫 feat: 초대하기 모달 구현
  api/config.ts
  api/dashboards/dashboards.types.ts
  api/dashboards/index.ts
  components/Dashboard/Column/Columns.tsx
  components/Modal/AlertModal.tsx
  components/Modal/KebabModal.tsx
  components/Modal/ModalContainer.tsx
  components/MyDashboardList.tsx
  components/Table/InvitationHistory.tsx
  components/Table/MemberList.tsx
Labels: 💫feat, 🍀refactor

#98 💫 feat: 할 일 생성 모달 기능 구현
  api/cards/cards.types.ts
  api/columns/columns.types.ts
  api/columns/index.ts
  api/config.ts
  components/Dashboard/Card/Card.tsx
  components/Dashboard/Column/Column.tsx
  components/Dashboard/Column/Columns.tsx
  components/Modal/AddTaskModal.tsx
  components/Modal/EditTaskModal.tsx
  components/Modal/ModalInput/ContactDropdown.tsx
  components/Modal/ModalInput/ImageUploadInput.tsx
  components/Modal/ModalInput/ModalInput.tsx
  components/Modal/ModalInput/TagInput.tsx
  components/Modal/TaskModal/TaskModal.tsx
  components/Modal/TodoModal.tsx
  components/common/Chip/ColumnName.tsx
  states/atoms.tsx
Labels: 💫feat, 🍀refactor

#99 💫feat: 대시보드 수정페이지 API 연결하기
  components/Account/AccountProfile.tsx
  components/Table/EditDashboard.tsx
  components/Table/InvitationHistory.tsx
  components/common/Buttons/BackButton.tsx
  components/common/Buttons/ButtonSet.tsx
Labels: 💫feat

#100 🛠️ fix: header 프로필 이미지 다르게 보이는 것 수정
  components/Dashboard/Card/Card.tsx
  components/Table/MemberList.tsx
  components/common/Nav/MemberListDropdown.tsx
  components/common/Nav/Profile.tsx
  components/common/Nav/ProfileImages.tsx
Labels: 🛠️fix, 🍀refactor

#102 💫 feat: AddTaskModal 추가 기능 구현
  api/cards/cards.types.ts
  components/Dashboard/Card/Card.tsx
  components/Modal/AddTaskModal.tsx
  components/Modal/ModalInput/ImageUploadInput.tsx
  components/Modal/ModalInput/ModalInput.tsx
Labels: 💫feat, 🍀refactor

#101 🍀 refactor: 컴포넌트2 수정사항 수정 중
  components/Modal/ModalContainer.tsx
  components/Modal/ModalWrapper.tsx
  components/Modal/TaskDropdown.tsx
  components/Modal/TaskModal/Comments.tsx
  components/Table/EditDashboard.tsx
  components/Table/MemberList.tsx
  components/common/Chip/DashBoardColor.tsx
  components/common/Nav/NavContainer.tsx
Labels: 🍀refactor

#104 💫 feat: 대시보드 삭제 기능 구현, 삭제완료시 리다이렉트
  api/config.ts
  api/dashboards/dashboards.types.ts
  api/dashboards/index.ts
  pages/dashboard/[boardid]/edit.tsx
Labels: 💫feat

#105 💫 feat: dashboard 페이지 card 무한 스크롤 구현
  components/Dashboard/Card/Card.tsx
  components/Dashboard/Column/Column.tsx
  components/Modal/AddTaskModal.tsx
  components/Modal/KebabModal.tsx
  components/Modal/TaskModal/TaskModal.tsx
  states/atoms.tsx
Labels: 💫feat

#106 🍀 refactor: editTaskModal 수정
  components/Modal/AddTaskModal.tsx
  components/Modal/EditTaskModal.tsx
  components/Modal/ModalInput/ContactDropdown.tsx
  components/Modal/ModalInput/DropdownList.tsx
  components/Modal/ModalInput/ModalInput.tsx
  components/Modal/ModalInput/StateDropdown.tsx
  components/Modal/ModalInput/TagInput.tsx
  components/Modal/TaskDropdown.tsx
  components/Modal/TaskModal/TaskModal.tsx
  states/atoms.tsx
  styles/ZindexStyles.ts
Labels: 🍀refactor

#107 💫 feat: 404 페이지 구현
  components/common/Nav/DashboardNav.tsx
  next.config.js
  pages/404/index.tsx
  pages/mydashboard/index.tsx
  pages/mypage/index.tsx
Labels: ❓question, 💫feat

#108 💫 feat: account profile 정보 수정 기능
  api/users/index.ts
  api/users/users.types.ts
  components/Account/AccountProfile.tsx
  components/Modal/AddTaskModal.tsx
  components/Modal/EditTaskModal.tsx
  components/Modal/ModalInput/ImageUploadInput.tsx
  states/atoms.tsx
Labels: 💫feat, 🤯help

#110 💫 feat : 태스크 수정 후 바로 반영
  api/cards/cards.types.ts
  components/Modal/AddTaskModal.tsx
  components/Modal/EditTaskModal.tsx
  components/Modal/ModalInput/ContactDropdown.tsx
  components/Modal/ModalInput/ImageUploadInput.tsx
  components/Modal/ModalInput/StateDropdown.tsx
  components/Modal/ModalInput/TagInput.tsx
  components/Modal/TaskModal/TaskModal.tsx
  states/atoms.tsx
Labels: 💫feat, 🍀refactor

#111 🍀 refactor: EditTaskModal 리팩
  components/Modal/AddTaskModal.tsx
  components/Modal/EditTaskModal.tsx
  components/Modal/ModalInput/ContactDropdown.tsx
  components/Modal/ModalInput/StateDropdown.tsx
  components/Modal/ModalInput/TagInput.tsx
  components/Modal/TaskModal/TaskModal.tsx
  components/Table/InvitedDashboard.tsx
  components/common/Chip/Tag.tsx
  states/atoms.tsx
Labels: 🍀refactor

#112 🍀 refactor: 헤더 버그랑...디자인 리팩
  components/common/Nav/MemberListDropdown.tsx
  components/common/Nav/NavContainer.tsx
  components/common/Nav/Profile.tsx
  components/common/Nav/ProfileImages.tsx
  styles/ZindexStyles.ts
Labels: 🍀refactor

#113 🍀 refactor: 대시보드 색깔, 이름 수정시 사이드메뉴 헤더 바로 반영
  api/dashboards/dashboards.types.ts
  api/dashboards/index.ts
  components/Table/EditDashboard.tsx
  components/common/Nav/DashboardNav.tsx
  components/common/SideMenu/SideMenu.tsx
  states/atoms.tsx
Labels: 🍀refactor

#114 🍀 refactor: Account Profile 기능 완성
  api/users/index.ts
  components/Account/AccountProfile.tsx
  components/Modal/KebabModal.tsx
  components/Modal/ModalInput/ImageUploadInput.tsx
  components/common/Nav/Profile.tsx
  states/atoms.tsx
  styles/ZindexStyles.ts
Labels: 💫feat

#117 🍀 refactor: 상태와 담당자 드롭다운 리팩토링
  components/Modal/ModalInput/ContactDropdown.tsx
  components/Modal/ModalInput/DropdownList.tsx
  components/Modal/ModalInput/StateDropdown.tsx
  styles/ZindexStyles.ts
Labels: 🍀refactor

#118 🛠️ fix: 이전 대시보드가 다른 대시보드에서 깜빡이는 현상
  components/Dashboard/Column/ColumnHeader.tsx
  components/Dashboard/Column/Columns.tsx
  components/Modal/KebabModal.tsx
  components/Modal/ModalInput/ModalInput.tsx
  components/Modal/TaskModal/Comments.tsx
  components/MyDashboardList.tsx
  components/common/Nav/DashboardNav.tsx
  pages/mydashboard/index.tsx
Labels: 🛠️fix, 🍀refactor

#119 🍀 refactor: 전반적으로 페이지 수정
  components/Account/AccountProfile.tsx
  components/Dashboard/Card/Card.tsx
  components/Dashboard/Column/Column.tsx
  components/Landing/MainSection.tsx
  components/Modal/AddTaskModal.tsx
  components/Modal/EditTaskModal.tsx
  components/Modal/KebabModal.tsx
  components/Modal/ModalInput/TagInput.tsx
  components/Modal/ModalWrapper.tsx
  components/Modal/TaskModal/Comments.tsx
  components/Modal/TaskModal/TaskModal.tsx
  components/MyDashboardList.tsx
  components/Table/EditDashboard.tsx
  components/Table/InvitedDashboard.tsx
  components/Table/MemberList.tsx
  components/common/Buttons/BackButton.tsx
  components/common/Buttons/Button.tsx
  components/common/Nav/MainNav.tsx
  components/common/Nav/MemberListDropdown.tsx
  components/common/Nav/NavContainer.tsx
  components/common/Nav/Profile.tsx
  components/common/Nav/SettingNav.tsx
  components/common/SideMenu/SettingSideMenu.tsx
  components/common/SideMenu/SideMenu.tsx
  pages/dashboard/[boardid]/edit.tsx
  pages/dashboard/[boardid]/index.tsx
  pages/mydashboard/index.tsx
  pages/mypage/index.tsx
  styles/GlobalStyles.ts
  styles/ZindexStyles.ts
Labels: 🧹chore, 🛠️fix, 🍀refactor, 🎨UI

#120 🍀 refactor: 테이블 삭제, 취소 시 헤더에 반영, 리랜더링
  components/Table/InvitationHistory.tsx
  components/Table/MemberList.tsx
  components/common/Nav/ProfileImages.tsx
  states/atoms.tsx
Labels: 🍀refactor

#121 🍀 refactor: 사이드메뉴, 댓글인풋 enter
  components/Modal/AddTaskModal.tsx
  components/Modal/EditTaskModal.tsx
  components/Modal/ModalInput/TagInput.tsx
  components/Modal/TaskModal/Comments.tsx
  components/MyDashboardList.tsx
  components/common/Chip/Tag.tsx
  components/common/Nav/NavContainer.tsx
  components/common/SideMenu/SideMenu.tsx
  constants/ColorConstant.ts
  states/atoms.tsx
Labels: 🍀refactor

#122 🍀 refactor: 메인 페이지 서비스 설명 및 이미지 교체
  assets/images/landing1.png
  assets/images/landing2.png
  assets/images/landing3.png
  assets/images/landing4.png
  assets/images/landing5.png
  components/Landing/MainSection.tsx
  components/Landing/Point1.tsx
  components/Landing/Point2.tsx
  components/Landing/Setting.tsx
Labels: 🍀refactor, 🎨UI

#124 🍀 refactor: 헤더 프로필 드롭다운 외부 클릭시 닫히도록 수정, z-index 리팩
  components/Modal/ModalInput/ContactDropdown.tsx
  components/common/Nav/Profile.tsx
  styles/ZindexStyles.ts
Labels: 🍀refactor

#125 🍀 refactor: 전반적으로 수정
  api/members/index.ts
  components/Dashboard/Column/Column.tsx
  components/Modal/ModalInput/ImageUploadInput.tsx
  components/Modal/ModalInput/ModalInput.tsx
  components/Modal/TaskModal/Comments.tsx
  components/Modal/TaskModal/TaskModal.tsx
  components/Table/EditDashboard.tsx
  components/Table/InvitationHistory.tsx
  components/Table/InvitedDashboard.tsx
  components/Table/MemberList.tsx
  components/common/Nav/MemberListDropdown.tsx
  components/common/Nav/NavContainer.tsx
  components/common/Nav/Profile.tsx
  components/common/NoProfileImage/ProfileImage.tsx
  components/common/SideMenu/SideMenu.tsx
  pages/dashboard/[boardid]/index.tsx
Labels: 🛠️fix, 🍀refactor, 🎨UI

#126 ⚒ fix: 초대받은 목록 렌더링 오류 해결
  components/Table/InvitedDashboard.tsx
Labels: 🛠️fix

#127 🍀 refactor: 초대자 오류 수정
  components/Table/InvitedDashboard.tsx
Labels: 🍀refactor

#130 🍀 refactor: 토스트 삽입 등
  api/auth/index.ts
  components/Account/AccountPassword.tsx
  components/Account/AccountProfile.tsx
  components/Modal/TaskModal/Comments.tsx
  components/Table/EditDashboard.tsx
  components/common/Nav/ProfileImages.tsx
  constants/InputConstant.ts
  pages/signin/index.tsx
Labels: 🍀refactor

#129 🧹 chore: README 작성
  README.md
Labels: 🧹chore

#131 🧹 chore: README 수정
  README.md
Labels: 🧹chore

#134 🍀Refactor : 댓글 작성자만 수정, 삭제하기 보이게 등
  components/Modal/TaskModal/Comments.tsx
Labels: 🍀refactor

#135 🧹 chore : README 최종 업데이트
  README.md
Labels: 🧹chore

#137 🧹 chore: README 완성
  README.md
Labels: 🧹chore

#138 🍀Refactor : 수정된 댓글은 수정됨 표시 보이게 하기
  components/Modal/TaskModal/Comments.tsx
Labels: 🍀refactor
